baseurl = "http://danielpietersen.com/"
canonifyurls = true
defaultcontentlanguage = "en"
disqusShortname = "thesyslog"
languagecode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "coder"
title = "The Syslog"
[[menu.main]]
name = "Projects"
url = "https://github.com/skowt"
weight = 3
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[params]
author = "Daniel Pietersen"
avatarurl = "images/avatar.jpg"
custom_css = []
description = "John Doe's personal website"
footercontent = "Enter a text here."
hideCopyright = false
hideCredits = false
info = "Rails Engineer & Sys Admin"
keywords = "blog,developer,personal"
rtl = false
[[params.social]]
icon = "fab fa-github fa-2x"
name = "Github"
url = "https://github.com/johndoe/"
weight = 1
[[params.social]]
icon = "fab fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/johndoe/"
weight = 2
